import json
import logging
import time
from typing import Dict, Any, List
from langchain_ollama import ChatOllama
from langchain_core.messages import AIMessage, ToolMessage, HumanMessage
from langgraph.types import interrupt
from graph.state import AgentState
from graph.tools import get_tools_for_role
from db.postgres import postgres_db
from config import settings

logger = logging.getLogger("backend.graph.nodes")

def _get_llm() -> ChatOllama:
    """Lazy-init LLM using Ollama. Connects to OLLAMA_BASE_URL with OLLAMA_MODEL."""
    return ChatOllama(
        model=settings.OLLAMA_MODEL,
        base_url=settings.OLLAMA_BASE_URL,
        temperature=0,
    )

async def llm_node(state: AgentState) -> Dict[str, Any]:
    """Call the LLM with role-filtered tools bound."""
    messages = state.get("messages", [])
    role = state.get("role", "viewer")
    
    # Filter tools dynamically based on user role
    tools = get_tools_for_role(role)
    
    # Bind tools to LLM
    llm = _get_llm()
    llm_with_tools = llm.bind_tools(tools) if tools else llm

    logger.info(f"Invoking LLM for user {state.get('user_id')} with role {role}...")
    response = await llm_with_tools.ainvoke(messages)
    
    return {
        "messages": [response],
        "current_step": "llm"
    }

async def tool_node(state: AgentState) -> Dict[str, Any]:
    """Execute tool calls generated by the LLM, with tenant injection and audit logging."""
    messages = state.get("messages", [])
    last_message = messages[-1]
    role = state.get("role", "viewer")
    tenant_id = state.get("tenant_id")
    token = state.get("token")
    conversation_id = state.get("conversation_id")
    
    if not isinstance(last_message, AIMessage) or not last_message.tool_calls:
        return {"current_step": "tools_skipped"}
        
    tool_results = []
    new_messages = []
    
    # Get tools available for the role
    tools_map = {t.name: t for t in get_tools_for_role(role)}
    
    for tool_call in last_message.tool_calls:
        tool_name = tool_call["name"]
        tool_args = tool_call["args"].copy()
        call_id = tool_call["id"]
        
        # Inject tenant_id and token for security/multi-tenancy if the tool expects them
        # Let's check parameters of the target tool in the tools_map
        if tool_name in tools_map:
            # Inject security variables securely from state
            tool_args["tenant_id"] = tenant_id
            if "token" in tools_map[tool_name].args:
                tool_args["token"] = token
                
        # --- Pre-execution hook for refunds > $1000 (Human-in-the-loop intercept) ---
        if tool_name == "refund_order_v1":
            order_id = tool_args.get("order_id")
            # To verify amount, we fetch order details from the MCP client directly
            from mcp_clients.orders import orders_mcp_client
            try:
                order_details = await orders_mcp_client.get_order_details(tenant_id, token, order_id)
                amount = order_details.get("amount", 0.0)
                
                # Check threshold
                if amount > 1000:
                    # Check if approval was already granted in state
                    pending = state.get("pending_approval")
                    if pending and pending.get("status") == "approved":
                        # Approved! Allow execution to proceed
                        logger.info(f"Refund of {amount} for order {order_id} has been APPROVED. Proceeding with refund.")
                    elif pending and pending.get("status") == "denied":
                        # Denied! Prevent execution and return error message
                        logger.warning(f"Refund of {amount} for order {order_id} was DENIED. Aborting execution.")
                        msg = ToolMessage(
                            content=json.dumps({"status": "error", "message": "Refund request denied by supervisor."}),
                            name=tool_name,
                            tool_call_id=call_id
                        )
                        new_messages.append(msg)
                        continue
                    else:
                        # No decision yet! Pause execution and flag approval_required
                        logger.info(f"Refund of {amount} for order {order_id} > 1000. Interrupting for approval.")
                        
                        # Set pending details in state to be returned to frontend
                        pending_details = {
                            "tool_name": tool_name,
                            "order_id": order_id,
                            "amount": amount,
                            "reason": tool_args.get("reason", "No reason provided"),
                            "status": "pending",
                            "tool_call_id": call_id,
                            "tool_args": tool_call["args"] # save original args
                        }
                        
                        # Return state update with approval_required = True
                        return {
                            "approval_required": True,
                            "pending_approval": pending_details,
                            "current_step": "approval_required"
                        }
            except Exception as e:
                logger.error(f"Error checking order details for refund approval: {e}")
                
        # Execute tool
        start_time = time.time()
        status = "success"
        
        if tool_name not in tools_map:
            output = f"Permission Denied: Tool '{tool_name}' is not allowed for your role."
            status = "permission_denied"
        else:
            try:
                logger.info(f"Executing tool {tool_name} with arguments {tool_args}...")
                target_tool = tools_map[tool_name]
                output = await target_tool.ainvoke(tool_args)
            except Exception as e:
                output = f"Error during tool execution: {str(e)}"
                status = "error"
                
        latency = int((time.time() - start_time) * 1000)
        
        # Log to PostgreSQL database (audit logs)
        try:
            await postgres_db.log_tool_execution(
                conversation_id=conversation_id,
                tool_name=tool_name,
                input_val=json.dumps(tool_call["args"]),
                output_val=str(output),
                latency_ms=latency,
                status=status
            )
        except Exception as e:
            logger.error(f"DB Logging error: {e}")
            
        msg = ToolMessage(
            content=str(output),
            name=tool_name,
            tool_call_id=call_id
        )
        new_messages.append(msg)
        
    return {
        "messages": new_messages,
        "current_step": "tools_executed"
    }

async def approval_node(state: AgentState) -> Dict[str, Any]:
    """Interruption node for Human-in-the-loop validation."""
    pending = state.get("pending_approval")
    if not pending:
        return {"approval_required": False, "current_step": "approval_bypass"}
        
    # Trigger graph interrupt
    logger.info("Triggering LangGraph interrupt for human approval...")
    response = interrupt({
        "type": "approval_request",
        "tool_name": pending["tool_name"],
        "order_id": pending["order_id"],
        "amount": pending["amount"],
        "reason": pending["reason"]
    })
    
    # Once resumed, response contains {"approved": True/False, "reviewer_id": "..."}
    approved = response.get("approved", False)
    reviewer_id = response.get("reviewer_id", "system")
    
    logger.info(f"Resumed from interrupt. Approved: {approved} by {reviewer_id}")
    
    # Update status in state
    pending["status"] = "approved" if approved else "denied"
    pending["reviewer_id"] = reviewer_id
    
    return {
        "approval_required": False,
        "pending_approval": pending,
        "current_step": "approval_resolved"
    }

async def response_node(state: AgentState) -> Dict[str, Any]:
    """Formulate final agent response and save to Postgres."""
    messages = state.get("messages", [])
    last_message = messages[-1]
    tenant_id = state.get("tenant_id")
    conversation_id = state.get("conversation_id")
    
    # Save final agent message to Database
    content = last_message.content if hasattr(last_message, "content") else str(last_message)
    try:
        await postgres_db.save_message(
            conversation_id=conversation_id,
            tenant_id=tenant_id,
            role="assistant",
            content=content
        )
    except Exception as e:
        logger.error(f"Failed to save assistant message to DB: {e}")
        
    return {
        "final_answer": content,
        "current_step": "completed"
    }

def router_node(state: AgentState) -> str:
    """Decide routing based on message state."""
    messages = state.get("messages", [])
    if not messages:
        return "llm"
        
    last_message = messages[-1]
    
    # If the LLM has generated tool calls, route to tool execution
    if isinstance(last_message, AIMessage) and last_message.tool_calls:
        # If approval is required, route to approval node first
        if state.get("approval_required"):
            return "approval"
        return "tools"
        
    # If it's a tool message or has no tool calls, return to LLM to formulate response
    if isinstance(last_message, ToolMessage):
        return "llm"
        
    # Otherwise, we are done
    return "response"
